spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

logging.level.root=INFO
logging.level.com.example.studentplacementmanagement=INFO

management.endpoint.health.show-details=always